name: Ci workflow
on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install
        run: npm Install
      - name: Build
        run: rpm run build
      - name: Tests
        run: npm test
